name: Server Test

on:
    push:
        branches:
            - main # Adjust this according to your default branch name

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              env:
                  DB_URL: ${{ secrets.DB_URL }}
                  DB_SERVICE_ROLE_KEY: ${{ secrets.DB_SERVICE_ROLE_KEY }}

            - name: Install dependencies
              run: |
                  cd server
                  npm install

            - name: Run tests
              run: |
                  cd server
                  npm test
